version: "3.9"
services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=user
      - MYSQL_DATABASE=test
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"


  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=test
      - MYSQL_PORT=3306

volumes:
  mariadb-data: